/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ConsoleContract } from "./Console";
import { MigrationsContract } from "./Migrations";
import { SecretRegistryContract } from "./SecretRegistry";
import { TokenContract } from "./Token";
import { TokenAContract } from "./TokenA";
import { XLNContract } from "./XLN";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "Console"): ConsoleContract;
      require(name: "Migrations"): MigrationsContract;
      require(name: "SecretRegistry"): SecretRegistryContract;
      require(name: "Token"): TokenContract;
      require(name: "TokenA"): TokenAContract;
      require(name: "XLN"): XLNContract;
    }
  }
}

export { ConsoleContract, ConsoleInstance } from "./Console";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
export {
  SecretRegistryContract,
  SecretRegistryInstance,
} from "./SecretRegistry";
export { TokenContract, TokenInstance } from "./Token";
export { TokenAContract, TokenAInstance } from "./TokenA";
export { XLNContract, XLNInstance } from "./XLN";
